---
driver:
  name: docker

provisioner:
  name: chef_zero
  data_bags_path: './../data_bags'

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[chef-provisioner]
    attributes:
